version: '3'
services:
  nodejs:
    image: deno96/nodejs:latest
    command: ["npm","start"]
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: "always"